TARGET    = status
SRC       = main.c
LIB_SRC   = display/jd9850.c display/gfx.c fonts/FreeSans12pt7b.c fonts/FreeMono9pt7b.c \
            power/power.c input/button.c vibrate/vibrate.c
SDK_EXTRA = components/driver/adc/adc.c
include ../../sdk/phy6222.mk
